spring:
  rabbitmq:
    host: 192.168.99.100

  jpa:
     generate-ddl: true
     show-sql: true
logging:
  level:
    com.rabbitmq: 'DEBUG'
    org.springframework.amqp: 'DEBUG'
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: 'INFO'
