spring:
  rabbitmq:
    host: 192.168.99.100

  jpa:
     generate-ddl: true
     show-sql: true

  devtools:
    livereload:
      enabled: true
server:
  port: 8080

logging:
  level:
    com.rabbitmq: 'INFO'
    org.springframework.amqp: 'INFO'
    org.hibernate: 'OFF'
    com.epages.SubscriberHandler: 'INFO'
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: 'INFO'
    org.springframework.amqp.rabbit.transaction.RabbitTransactionManager: 'DEBUG'
    org.springframework.transaction.support.TransactionSynchronizationManager: 'TRACE'
    org.springframework.amqp.rabbit.connection.RabbitResourceHolder: 'TRACE'
